# Site settings
title: Willson Davis co.
email: danielkrex@gmail.com
description: "Willson Davis co. test site"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: #
  - title: github
    url: #
  - title: envelope
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: TEXAS
  - line: USA

# Build settings
markdown: kramdown
permalink: pretty
